blinking-cursor = false
performance = "High"
disable-unfocused-render = false
use-fork = false
use-kitty-keyboard-protocol = false
line-height = 1.0
theme = ""
padding-x = 10.0
cursor = "▇"
scroll-multiplier = 3.0
env-vars = []
option-as-alt = "Left"
ignore-selection-foreground-color = false

[navigation]
mode = "CollapsedTab"
use-current-path = false

[window]
width = 600
height = 400
mode = "Windowed"

[background]

[shell]
program = ""
args = ["--login"]

[fonts]
size = 18.0
extras = []

[fonts.regular]
family = "JetBrainsMono Nerd Font Mono"
weight = 400
style = "normal"

[fonts.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "JetBrainsMonoNL Nerd Font Mono"
weight = 800
style = "italic"

[fonts.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []

